env = GDK_BACKEND, wayland,x11,*
env = QT_QPA_PLATFORM, wayland;xcb
env = SDL_VIDEODRIVER, wayland
env = CLUTTER_BACKEND, wayland

env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

env = QT_QPA_PLATFORM, wayland;xcb
env = QT_QPA_PLATFORMTHEME, qt5ct

env = GTK_THEME, Catppuccin-Mocha-Standard-Mauve-Dark
env = XCURSOR_THEME, Bibata-Modern-Classic
env = XCURSOR_SIZE, 24
